apiVersion: v1
kind: ServiceAccount
metadata:
  name: ischaos-sa
  namespace: ischaos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ischaos-reader
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "services", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ischaos-reader-binding
subjects:
  - kind: ServiceAccount
    name: ischaos-sa
    namespace: ischaos
roleRef:
  kind: ClusterRole
  name: ischaos-reader
  apiGroup: rbac.authorization.k8s.io
