apiVersion: v1
kind: Service
metadata:
  name: ischaos-platform
  namespace: ischaos
spec:
  type: NodePort
  selector:
    app: ischaos-platform
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30580
